# Generated by ChatGPT

import sys
from pathlib import Path
import types
import pytest

from coverup import utils
import coverup.test_writer_agent as writer_agent
from coverup.test_writer_agent import build_prompt, generate_tests


def test_build_prompt_includes_context(tmp_path, monkeypatch):
    # Create source and test files
    rel_src_file = Path("pkg/mod.py")
    rel_test_file = Path("tests/coverup/test_mod.py")
    src_file = tmp_path / rel_src_file
    test_file = tmp_path / rel_test_file
    src_file.parent.mkdir(parents=True, exist_ok=True)
    test_file.parent.mkdir(parents=True, exist_ok=True)
    src_file.write_text("line1\nline2\nline3", encoding="utf-8")
    test_file.write_text("old test content", encoding="utf-8")

    # Stub enumerate_lines
    def fake_enumerate_lines(text):
        return [f"{i+1}: {line}" for i, line in enumerate(text.splitlines())]

    monkeypatch.setattr(utils, "enumerate_lines", fake_enumerate_lines)

    # Patch template read
    original_read_text = Path.read_text

    def patched_read_text(self, *args, **kwargs):
        if str(self).endswith("coverup/prompts/create_tests.md.j2"):
            return (
                "ENUM:\n{{ enumerated_source }}\n"
                "EXIST:\n{{ existing_tests }}\n"
                "MISS:\n{{ missing_lines }}\n"
                "PFT:\n{{ previous_failed_tests }}\n"
                "PERR:\n{{ previous_errors }}\n"
                "SRC:\n{{ source_filepath }}\n"
            )
        return original_read_text(self, *args, **kwargs)

    monkeypatch.setattr(Path, "read_text", patched_read_text, raising=False)

    # File coverage stub
    class FileCoverageStub:
        def __init__(self, missing_lines):
            self.missing_lines = missing_lines

    file_coverage = FileCoverageStub([1, 3])

    # Test report stub
    class TestStub:
        def __init__(self, name, error):
            self.name = name
            self.error = error

    class TestReportStub:
        def getFailedTests(self):
            return [
                TestStub(f"{str(rel_test_file)}::test_one", "E1"),
                TestStub("other_test.py::test_two", "E2"),
            ]

    test_report = TestReportStub()

    # Build prompt
    prompt = build_prompt(
        rel_src_file=rel_src_file,
        rel_test_file=rel_test_file,
        src_file=src_file,
        test_file=test_file,
        file_coverage=file_coverage,
        test_report=test_report,
    )

    # Assertions
    assert "1: line1" in prompt and "3: line3" in prompt
    assert "old test content" in prompt
    assert f"{str(rel_test_file)}::test_one" in prompt and "other_test.py::test_two" not in prompt
    assert "E1" in prompt and "E2" in prompt
    assert str(rel_src_file) in prompt


def test_generate_tests_writes_file_and_calls_llm(tmp_path, monkeypatch):
    # Ensure tests directory exists
    (tmp_path / "tests" / "coverup").mkdir(parents=True, exist_ok=True)

    # Monkeypatch utils.create_test_file to return a specific path
    def fake_create_test_file(rel_src_file, test_dir, project_root):
        return Path("tests/coverup/test_mod_gen.py")

    monkeypatch.setattr(utils, "create_test_file", fake_create_test_file)

    # Monkeypatch build_prompt to avoid depending on filesystem/template
    monkeypatch.setattr(writer_agent, "build_prompt", lambda **kwargs: "PROMPT")

    # LLM stub
    class DummyLLM:
        model = "dummy-model"

        def __init__(self):
            self.prompts = []

        def call(self, prompt):
            self.prompts.append(prompt)
            return "LLM_TESTS"

    llm = DummyLLM()

    # Call generate_tests
    result_path = generate_tests(
        project_root=tmp_path,
        rel_src_file=Path("pkg/mod.py"),
        file_coverage=None,
        test_report=types.SimpleNamespace(getFailedTests=lambda: None),
        llm_caller=llm,
    )

    # Assertions
    expected_path = tmp_path / "tests/coverup/test_mod_gen.py"
    assert result_path == expected_path
    assert expected_path.read_text(encoding="utf-8") == "LLM_TESTS"
    assert llm.prompts == ["PROMPT"]